### ISSUE TITLE
Best practice for infinite vertical rule

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#32]
I'd like to add a vertical line to a plot and have it always be visible - what's the best way to accomplish this - just put very small/large values for the ymin/ymax? Is there a way to write infinities?

**Comment by slowe** [comment]
[According to the Vega spec](https://vega.github.io/vega-lite/docs/rule.html#widthheight-spanning-rules):

> If the rule mark only has y encoding, the output view produces horizontal rules that spans the complete width. Similarly, if the rule mark only has x encoding, the output view produces vertical rules that spans the height.

Our interpretation doesn't currently cope with unset x or y values as they appear as NaN.

**Comment by slowe** [comment]
This is now implemented. Any rules with only an x-value defined will use the full y-axis range. Similarly, rules with only a y-value defined will use the full x-axis range. See the [basic example](https://aperiosoftware.github.io/timeseries.js/basic) which uses [lightcurve2.json](https://github.com/aperiosoftware/timeseries.js/blob/master/data/lightcurve2.json) for configuration.

**Comment by astrofrog** [comment]
@slowe - thanks! Can something similar be done for ranges, or is that not possible since those are just rectangles and need all four sides defined?

**Comment by slowe** [comment]
I hadn't noticed that this was actually from the VEGA-Lite spec not the VEGA spec.

**Comment by astrofrog** [comment]
Just out of curiosity, which features from Vega and not Vega lite do we use currently? A while back we said we'd do Vega initially but then check whether we could get away with using Vega lite as a basis - is that feasible or do we use features of Vega that aren't in Vega lite?

**Comment by slowe** [comment]
I can't really remember. What is the advantage of using Vega Lite over Vega? It would be a large amount of work to switch now.

As Vega Lite JSON compiles into Vega JSON, we just need to work out how Vega Lite fills in the missing axis values and recreate that.

**Comment by astrofrog** [comment]
> As Vega Lite JSON compiles into Vega JSON, we just need to work out how Vega Lite fills in the missing axis values and recreate that.

I agree this makes more sense - ignore my suggestion :)

**Comment by slowe** [comment]
OK, so I've realised that in defining the x/y/x2/y2 values in a mark, Vega takes into account `scale` to decide how to process the `value`. If `scale` is not defined, it seems to treat it as a pixel value. I'll simplify our use cases to either a rule that has a defined range (in data values) or one that always stretches to a side of the graph. A defined range works as before. 

An infinite **vertical rule** would have the properties that look like this:

`"x": { "scale": "xscale", "signal": "datetime(2018,9,29,13,53,22)" },`
`"y": { "value": 0 },`
`"y2": { "field": { "group": "height" } },`

In this case the `x` requires a `scale` otherwise you'll get odd behaviour. I should note that I'm only checking `scale` is set not that it has the right value (to keep things fast). But it will need to be the right value to open in Vega.

An infinite **horizontal rule** would be defined something like this:

`"y": { "scale": "yscale", "value": 1 },`
`"x": { "value": 0 },`
`"x2": { "field": { "group": "width" } },`

Where the `y` needs `scale` to be set.

I've updated the mark examples. **Make sure that any existing `x`, `y`, `x1`,`x2`,`y1`,`y2` properties have a `scale` set** if they don't already.
