### ISSUE TITLE
PNG background

### ISSUE THREAD

**Issue by SolarDrew** [aperiosoftware/timeseries.js#37]
Saving a PNG of the plot exports the background as transparent - I assume this it's supposed to be white.

**Comment by slowe** [comment]
@SolarDrew I'd deliberately kept it as transparent. My reasoning was that it is easy for people to add a white background to it after download (in powerpoint, a graphics editor, a webpage etc) but they can't cleanly make it transparent again (due to the anti-aliasing). On the page it is actually transparent and is just showing the white of the page behind it. However, if we want it to always have a white background I can force it to. Or perhaps we could have "Save as PNG" and "Save as transparent PNG" buttons?

**Comment by slowe** [comment]
I've added an extra save button so it can be saved with either a white background (`Save as PNG`) or transparent background (`Save as transparent PNG`). Does that work for you? [Example](https://aperiosoftware.github.io/timeseries.js/basic)

**Comment by slowe** [comment]
Hmm. It was working when I commented 2 days ago. Not sure what has changed. I'll have a look.

**Comment by slowe** [comment]
OK. It should be fixed now :)

**Comment by SolarDrew** [comment]
Yep, that works, thanks :) Unfortunately it does also enlarge most of the points and a lot of the bars:

![timeseries-5](https://user-images.githubusercontent.com/1914702/51708653-50e70000-201c-11e9-9b07-b23b0d129447.png)

I assume this is a separate thing, but is it a known issue? It doesn't seem to do it for the transparent background.

**Comment by slowe** [comment]
It was not a known issue. Basically, to create a white-background-canvas things had to be re-drawn first but, as everything wasn't reset first (resetting everything at every step can lead to significant overhead) *all* the hover styles were being applied to the data. This didn't happen if you wanted a transparent background as nothing needed to be re-drawn in that case. Mark styles are now reset during this re-draw so the issue shouldn't exist.
