### ISSUE TITLE
Rendering of line is sometimes spikey

### ISSUE THREAD

**Issue by astrofrog** [aperiosoftware/timeseries.js#67]
As discussed in person a couple of weeks back, the rendering of the lines appears to depend on the zoom level, although in some cases mixed rendering can be seen in a single view:

<img width="1142" alt="Screenshot 2019-05-05 at 19 07 06" src="https://user-images.githubusercontent.com/314716/57198313-15d46100-6f69-11e9-8094-437c24e14073.png">

**Comment by slowe** [comment]
As we are basically calling the canvas api - `moveTo` and `lineTo` - it isn't obvious what the problem is. It may be down to [lineCap] or to some kind of sub-pixel issue. I'll set up a specific canvas test to see if I can replicate it and find a fix.

**Comment by slowe** [comment]
As you can see in [this test](https://aperiosoftware.github.io/timeseries.js/tests/issue67), it turned out to be down to [`lineJoin`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin). The default (`mitre`) extends the two line segments out until they join. The options `bevel` and `round` both give better renderings but `bevel` seems slightly more compact.

- `mitre` ![lineJoin-mitre](https://user-images.githubusercontent.com/299787/58027410-7a1e2580-7b10-11e9-8270-3d671ec59ef2.png)
- `round` ![lineJoin-round](https://user-images.githubusercontent.com/299787/58027417-7f7b7000-7b10-11e9-9d41-f8fd258f26d0.png)
- `bevel` ![lineJoin-bevel](https://user-images.githubusercontent.com/299787/58027453-915d1300-7b10-11e9-862e-b1a1d3325d21.png)


All three seem to take a similar time to render on the canvas. However, `round` and `bevel` should give a slight speed boost as the step which calculates the pixel lookup table has slightly less work to do as fewer pixels are drawn. We've gone with `bevel`.

**Comment by astrofrog** [comment]
Looks great!
